name: create README

on:
  workflow_dispatch:
  schedule:
  - cron: "1 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Update README
      env:
        README_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        python japanese_wotd/fetch_wotd.py
        cat README.md
        
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "Updated content" || exit 0
        git push
